POST localhost:8080//api/auth/register HTTP/1.1
Host: your-api-host.com
Content-Type: application/json

{
  "firstName": "John",
  "lastName": "Doe",
  "email": "johndoe@example.com",
  "password": "password123",
  "role": "USER",
  "phone": "1234567890"
}


###

POST localhost:8080/api/auth/token HTTP/1.1
Host: your-api-host.com
Content-Type: application/json

{
  "email": "johndoe@example.com",
  "password": "password123"
}
